name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.5
      with:
        rust-version: 1.61.0
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Publish to crates.io
      run: cargo publish
