name: Rust

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Rustup and Rust
      # You may pin to the exact commit or the version.
      # uses: MatteoH2O1999/setup-rust@4ad9ba15361cf3d4daa8ed327880249e09ecc715
      uses: MatteoH2O1999/setup-rust@v1.0.1
      with:
        # The rust release channel to install
        channel: stable
        # The rust profile to install (minimal, default or complete)
        profile: minimal
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
